name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

# Define environment variables available to all jobs
env:
  NODE_VERSION: '20'

permissions:
  contents: write # Changed to write for release creation
  pull-requests: write
  deployments: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history and tags
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: TypeScript Check
      run: tsc --noEmit
    
    - name: Lint Check
      run: npm run lint
      
    - name: Build Check
      run: npm run build

  # Vercel handles test deployments automatically
  # We only need to wait for its status check in production deployment

  deploy-production:
    name: Deploy to Production
    needs: [test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: Live
      url: https://createdao.org
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get Version
      id: get_version
      run: |
        git fetch --tags
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0")
        echo "VERSION=${LATEST_TAG}" >> $GITHUB_OUTPUT

    # Get Vercel Preview URL
    - name: Get Vercel Preview URL
      uses: zentered/vercel-preview-url@v1.1.9
      id: vercel_preview_url
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        GITHUB_REF: "main"
        GITHUB_REPOSITORY: ${{ github.repository }}
      with:
        vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}

    # Wait for Vercel deployment to be ready
    - name: Wait for Vercel Deployment
      uses: UnlyEd/github-action-await-vercel@v1
      id: await-vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      with:
        deployment-url: ${{ steps.vercel_preview_url.outputs.preview_url }}
        timeout: 420 # 7 minutes
        poll-interval: 15

    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          git fetch origin
          git checkout main
          git pull origin main
          echo "VITE_COMMIT_HASH=${GITHUB_SHA}" >> .env
          echo "VITE_APP_VERSION=${{ steps.get_version.outputs.VERSION }}" >> .env
          docker-compose up -d --build

    - name: Purge Cloudflare Cache
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}'

    - name: Create Release
      if: success()
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          Production deployment of version ${{ steps.get_version.outputs.VERSION }}
          Commit: ${{ github.sha }}
        draft: false
        prerelease: false
